@startuml Use cases
title Prix Goncourt 2025 - Use Case Diagram

left to right direction

actor "Utilisateur" as User
actor "Président du jury" as President
actor "Membre du jury\n" as Member

rectangle "Application Prix Goncourt 2025" {

  usecase "Consulter une sélection" as UC1
  usecase "Consulter le détail\nd'un livre" as UC2
  usecase "Consulter les résultats\ndu dernier tour" as UC3

  usecase "Indiquer les livres\nde la 2e sélection" as UC4
  usecase "Indiquer les livres\nde la 3e sélection" as UC5
  usecase "Saisir les votes\npour le dernier tour" as UC6

  usecase "S'authentifier\n" as UC7
  usecase "Voter pour la 2e sélection\n" as UC8
  usecase "Voter pour la 3e sélection\n" as UC9
  usecase "Voter pour le lauréat\n" as UC10
}

User --> UC1
User --> UC2
User --> UC3

President --> UC4
President --> UC5
President --> UC6
President --> UC3

Member --> UC7
Member --> UC8
Member --> UC9
Member --> UC10

UC1 --> UC2 : <<include>>
UC6 --> UC3 : <<include>>

@enduml
